from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('blog_classic_1_right/', Blog_classic_1_right.as_view(), name='Blog_Classic_Right1'),
    path('Blog_classic_1/',Blog_classic_1.as_view(), name='Blog_Classic_1'),
    path('Blog_grid_2_left/', Blog_grid_2_left.as_view(), name='Blog_Grid_2'),
    path('Blog_grid_2_columns/', Blog_grid_2_columns.as_view(), name='Blog_Grid_2_Columns'),
    path('Blog_grid_3_columns_right/', Blog_grid_3_columns_right.as_view(), name='Blog_Grid_3_Columns_Right'),
    path('Blog_grid_3_columns/', Blog_grid_3_columns.as_view(), name='Blog_Grid_3_Columns'),
    path('Blog_grid_4/', Blog_grid_4.as_view(), name='Blog_grid_4'),
    path('Blog_masonry_2_right/', Blog_masonry_2_right.as_view(), name='Blog_masonry_2_right'),
    path('Blog_masonry_2/', Blog_masonry_2.as_view(), name='Blog_masonry_2'),
    path('Blog_masonry_3_left/', Blog_masonry_3_left.as_view(), name='Blog_masonry_3_left'),
    path('Blog_masonry_3/', Blog_masonry_3.as_view(), name='Blog_masonry_3'),
    path('Blog_masonry_4/', Blog_masonry_4.as_view(), name='Blog_masonry_4'),
    path('Blog_single_audio_post/', Blog_single_audio_post.as_view(), name='Blog_single_audio_post'),
    path('Blog_single_blockquote/', Blog_single_blockquote.as_view(), name='Blog_single_blockquote'),
    path('Blog_single_full_width/', Blog_single_full_width.as_view(), name='Blog_single_full_width'),
    path('Blog_single_image_slideshow_post/', Blog_single_image_slideshow_post.as_view, name='Blog_single_image_slideshow_post'),
    path('Blog_single_link_post/', Blog_single_link_post.as_view(), name='Blog_single_link_post'),
    path('Blog_single_right_sidebar/', Blog_single_right_sidebar.as_view(), name='Blog_single_right_sidebar'),
    path('Blog_single_video_post/', Blog_single_video_post.as_view(), name='Blog_single_video_post'),
    path('index_agency/', index_agency.as_view(), name='index_agency'),
    path('index_boxed_static_video/', index_boxed_static_video.as_view(), name='index_boxed_static_video'),
    path('index_landing/', index_landing.as_view(), name='index_landing'),
    path('index_magazine/', index_magazine.as_view(), name='index_magazine'),
    path('index_other_head_static_content/', index_other_head_static_content.as_view(), name='index_other_head_static_content'),
    path('index_portfolio/', index_portfolio.as_view(), name=''),
    path('index_side_menu/', index_side_menu.as_view(), name='index_side_menu'),
    path('index_static_image', index_static_image.as_view(), name='index_static_image'),
    path('index_text_and_form', index_text_and_form.as_view(), name='index_text_and_form'),
    path('index_video_background', index_video_background.as_view(), name='index_video_background'),
    path('index_video_in_popup', index_video_in_popup.as_view(), name='index_video_in_popup')
]
